

version: '3'

services:
  nginx:
    build: ./nginx
    command: [nginx, '-g', 'daemon off;']
    ports:
      - 80:80
    volumes:
      - staticvolume:/collected-static
    networks: 
      - nginx_network
    depends_on:
      - web
